apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"

spec:
  project: default

  source:
    repoURL: https://github.com/rahulmoorthy786/devboard.git
    targetRevision: mega-project
    path: gitops/observability/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  ignoreDifferences:
    - group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: proxy-telemetry
      namespace: envoy-gateway-system
      jsonPointers:
        - /spec/logging
        - /spec/telemetry/tracing/provider/backendRefs/0/group
        - /spec/telemetry/tracing/provider/backendRefs/0/kind
        - /spec/telemetry/tracing/provider/port
        - /spec/telemetry/accessLog/settings/0/sinks/0/openTelemetry/backendRefs/0/group
        - /spec/telemetry/accessLog/settings/0/sinks/0/openTelemetry/backendRefs/0/kind
        - /spec/telemetry/accessLog/settings/0/sinks/0/openTelemetry/port

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
