# Goal - I have to ensure the packages and dependencies have been audited for any vulnerabilities.

name: Dependency Scan

on:
    workflow_call:

jobs:
    dependency-scan:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v7
            
          - name: Setup Go
            uses: actions/setup-go@v6 
            with:
                go-version: 1.22
                go-version-file: 'go.mod'
                cache-dependency-path: 'go.sum'
                
          - name: Install Govulncheck
            run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
            
          - name: Run Govulncheck
            continue-on-error: true
            run: govulncheck ./...  > govulncheck-report.txt
            working-directory: backend

          - name: Setup node
            uses: actions/setup-node@v6 
            with:
                node-version: '20'
                cache: npm
                cache-dependency-path: frontend/package-lock.json
                
          - name: Run dependency scan for node packages
            run: npm audit
            working-directory: frontend
            

          - name: Upload Test Report
            if: always() # Ensure report uploads even if the job fails
            uses: actions/upload-artifact@v4
            with:
                name: job-report
                path: reports/govulncheck-report.txt
                retention-days: 5