# Goal - To run end to end DevSecops CI pipeline

name: DevSecOps CI

on:
    push:
        branches: [main]

jobs:
    # code stage (with shift-left approach)
    code-quality:
        uses: ./.github/workflows/code-quality.yml       

    # Security Scans
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    # Dependency Checks
    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yml  

    # Docker Checks        
    docker-checks:
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit
        
    # Sonar Scan
    sonar_qube_scan:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit

    code-test:
        uses: ./.github/workflows/code-test.yml
        
    docker-push:
         needs: [code-quality, secret-scanning, dependency-checks, docker-checks, sonar_qube_scan, code-test]
         uses: ./.github/workflows/docker-push.yml
         secrets: inherit


    deploy:
        needs: [docker-push]
        uses: ./.github/workflows/deploy.yml
        secrets: inherit      