# Goal - To check whether the application code coverage doesnt have security vulnerabilities. 

name: Sonar Scan

on:
    workflow_call:

jobs:
    sonar-scanner:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v7
            
          - name: Sonar Scan
            uses: SonarSource/sonarqube-scan-action@v8.2.0
            env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}